[build]
  command = "yarn build" # the command you run to build this file
  publish="/build"
  base = ""
  
[context.development.environment]
REACT_APP_STAGE = “development”
[context.staging.environment]
REACT_APP_STAGE = “staging”
[context.production.environment]
REACT_APP_STAGE = “production”

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200